### ISSUE TITLE
Inertia React state not isset.

### ISSUE THREAD

**Issue by viktor-nemeth** [spatie/medialibrary.pro#39]
Media data not showing because react state not isset in inertia.
The state constant respond:
[
<img width="472" alt="Képernyőfotó 2021-04-20 - 22 05 23" src="https://user-images.githubusercontent.com/61492806/115457242-893e0e80-a224-11eb-824f-7d2ef40f7bbf.png">
](url)

**Comment by freekmurze** [comment]
Please open up an issue at https://github.com/spatie/laravel-medialibrary-pro. If you don't have access to that repo, connect your spatie.be account to GitHub.
