### ISSUE TITLE
Laravel/livewire/jetstream with media lib pro not even rendering upload element

### ISSUE THREAD

**Issue by rstanislav** [spatie/medialibrary.pro#41]
Hello! 
I have license for pro version, using media lib for media handling without any problems, tried to use pro for uploads today and could not get it to even render, attached image how it looks like.
css is loading, no errors in console, spend like 5 hours searching and can't find why its not working.
![photo_2021-09-24_21-31-29](https://user-images.githubusercontent.com/1781042/134723728-1221c6cf-76ee-495d-9f00-5351b82b1af5.jpg)

**Comment by AdrianMrn** [comment]
This looks like you're missing the CSS styles! Could you compare your setup to the demo application, or try installing the library in a new, clean Laravel app please?

**Comment by Edirisinghe** [comment]
@AdrianMrn was you able to fix this? I have same issue
