### ISSUE TITLE
Continued use after licence expiry

### ISSUE THREAD

**Issue by Riaan-ZA** [spatie/medialibrary.pro#44]
Hi. The docs state that the library can continue to be used after expiry, but will no longer be updated. I'm using the scripts in my front end repository, installed using NPM, but since the license has expired, any npm updates now fail, even if I try lock the @spatie scripts at their current version.

```
npm package "media-library-pro-core" does not exist under owner "spatie"
```

So my question is how can I continue to use this package at the currently installed version without it preventing me from running npm update or npm install?

**Comment by AdrianMrn** [comment]
@Riaan-ZA We'll take a look at this asap. You'll probably have to remove the package from your dependencies and place the files in your app. For now, copy the files you have in your node_modules and place them in an e.g. `vendor` folder in your app.

**Comment by freekmurze** [comment]
I've added instructions for the PHP side of things here: https://spatie.be/docs/laravel-medialibrary/v9/handling-uploads-with-media-library-pro/installation#what-happens-when-your-license-expires

**Comment by AdrianMrn** [comment]
I believe this also covers the JS side, if the download includes everything that is publish on packagist!
