### ISSUE TITLE
x-media-library-attachment is  not rendering 

### ISSUE THREAD

**Issue by Edirisinghe** [spatie/medialibrary.pro#45]
I have the "x-media-library-attachment "  component on my page but It is rendering like the below image(screenshot 1).  CSS file in the right place (I guess -screenshot 1). What I have missed? 

**screenshot 1**

![image](https://user-images.githubusercontent.com/1161905/145949829-99bc8a31-3a92-4b63-b94a-e18a42e2e49d.png)
**screenshot 2**

![image](https://user-images.githubusercontent.com/1161905/145950386-7a645472-de3d-4377-b8dc-799c1d048bc3.png)

**Comment by AdrianMrn** [comment]
Make sure you've loaded in the livewire scripts before the component. If you open your browser console, you'll most likely see an error message.

Let me know if this doesn't fix your issue!

**Comment by Edirisinghe** [comment]
@AdrianMrn console doesn't show any error 

![tempsnip](https://user-images.githubusercontent.com/1161905/145959013-810b2455-97ab-4ccf-9ed2-793c9da1e8a2.png)
**code like this  inspection windows** 
![image](https://user-images.githubusercontent.com/1161905/145958518-7461ffe1-e5a0-4ad0-a9a5-69167136fdb3.png)
