### ISSUE TITLE
Sort on x-media-library-collection stops working after 15 items

### ISSUE THREAD

**Issue by scottmetoyer** [spatie/medialibrary.pro#46]
I am seeing strange behavior on a Laravel Livewire project I inherited that uses the x-media-library-collection component.

Everything works perfectly if the media collection is 15 or less items in size. Collections with 16 or more items will not drag/sort correctly. After a drag is completed the list will resort itself randomly and not retain the set order. Looking at the media table shows values in the order_column that do not match what I'm seeing on the screen. I'm on version 1.17.7 of Media Library Pro.

Any ideas what I'm doing wrong?

**Comment by freekmurze** [comment]
That's strange. I tried to recreate the problem using our demo app, but it seems to be working. Could you try it there as well?

https://github.com/spatie/laravel-medialibrary-pro-app

<img width="1017" alt="CleanShot 2022-03-24 at 10 29 48@2x" src="https://user-images.githubusercontent.com/483853/159885947-2d34ed31-9730-41d0-8ca2-aa6245de5f65.png">

**Comment by massimomarazzi** [comment]
Hi There,
same here, when upload 15+ media then save and after reoder one media,  other media are sortete randomly....

Laravel 8.74
Php 7.4.28
medialibrary 9.11.2
medialibrary-pro 1.17.13

I'am using livewire component .
Short screencast here [https://web.tresorit.com/l/mAlZC#ONvLXz3B_17zst5xSQG4Bw](https://web.tresorit.com/l/mAlZC#ONvLXz3B_17zst5xSQG4Bw)
